theme = "modern"
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon $swap_used_percents "

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "load"
interval = 1
format = " $icon $1m "

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "net"
device = "wlp3s0"
format = " $icon $signal_strength $ssid $speed_down $speed_up "
interval = 5

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
